language: ruby
rvm:
    - 2.6.3

before_script:
    - chmod +x ./script/cibuild.sh # or do this locally and commit
    - chmod +x ./script/after_deploy.sh

after_deploy: ./script/after_deploy.sh

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./script/cibuild.sh

# branch whitelist, only for GitHub Pages
branches:
    only:
        - master        # test the master branch
        - gh-pages      # test the gh-pages branch
        - /pages-(.*)/  # test every branch which starts with "pages-"

addons:
    apt:
        packages:
            - libcurl4-openssl-dev

cache: bundler # caching bundler gem packages will speed up build

# Optional: disable email notifications about the outcome of your builds
notifications:
    email: false

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep_history: true
    on:
        branch: master
    local_dir: ./_site
    target_branch: gh-pages